# simply protect the web server
users:
    admin: admin
# secret for flask state store
flask:
  secret: supersecret
# plugins to trigger than a picture is take and store the resulting picture
plugins:
#- picamera_collector.ap_plugins.store_multicast
- picamera_collector.ap_plugins.store_to_gcs
#- picamera_collector.ap_plugins.light_control
#- picamera_collector.ap_plugins.event_gpio
- picamera_collector.ap_plugins.event_webio
# possible resolutions (standards)
resolution:
- 640x480
- 1280x720
- 1640x922
- 1640x1232
- 1920x1080
- 3280x2464
# standard camera modes
modeList:
- auto
- sports
# list o posible ISO settings
isoList:
- 0
- 100
- 200
- 400
- 800
- 1600
# compressio quality of jpeg file
jpegquality:
- 20
- 50
- 85
- 100
methodList:
- picture
- video