# simply protect the web server
users:
    admin: admin
# secret for flask state store
flask:
  secret: supersecret
# plugins to trigger than a picture is take and store the resulting picture
plugins:
- ap_plugins.store_to_gcs
- ap_plugins.light_control
# if the triger is on a remote host where is the camaera
camerahost: picameradev
# initial setting for camera on boot 
initial_settings:
 resolution: 1920x1080
 mode: auto
 iso: 0
 jpegquality : 85
 numberimages : 2
 delay : 2
# possible resolutions (standards)
resolution:
- 640x480
- 1280x720
- 1640x922
- 1640x1232
- 1920x1080
- 3280x2464
# standard camera modes
modeList:
- auto
- sports
# list o posible ISO settings
isoList:
- 0
- 100
- 200
- 400
- 800
- 1600
# compressio quality of jpeg file
jpegquality:
- 85
- 90
- 95
- 100