users:
    admin: admin
flask:
  secret: supersecret
plugins:
  event: ap_plugins.event_gpio 
  store: ap_plugins.store_to_gcs
gcs:
  authfile: /home/pi/gdiaunicorn-a4464e10106e.json
  bucket: roof_images
  directory: test
initial_settings:
 resolution: 1920x1080
 mode: auto
 iso: 0
 jpegquality : 85
resolution:
- 640x480
- 1280x720
- 1640x922
- 1640x1232
- 1920x1080
- 3280x2464
modeList:
- auto
- sports
isoList:
- 0
- 100
- 200
- 400
- 800
- 1600
jpegquality:
- 85
- 90
- 95
- 100